title: Khouloud Portfolio
email: khouloud.beydoun01@stclairconnect.ca
baseurl: "https://khellow.github.io/Khouloud/"
url: "https://www.instagram.com/roses.for.me/"

 
  collections:
  illustrations:
    output: true
    permalink: /:collection/:path/
     
  photography:
    output: true
    permalink: /:collection/:path/
      
  design:
    output: true
    permalink: /:collection/:path/
      

sass:
  style: compact # possible values: nested expanded compact compressed
  
