title: Khouloud Portfolio
email: khouloud.beydoun01@stclairconnect.ca
baseurl: "https://khellow.github.io/Khouloud/"
url: "https://khellow.github.io/Khouloud/"
sass:
  style: compact
 
  collections:
  illustrations:
    output: true
    permalink: /:collection/:path/
     
  photography:
    output: true
    permalink: /:collection/:path/
      
  design:
    output: true
    permalink: /:collection/:path/
      


  
